# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=26.2-1.0.3
mod_version=1.0.3
group=cn.com.fakeneko
java_version=25

# Common
minecraft_version=26.2
mod_name=Auto Switch Elytra
mod_author=fakeneko
mod_id=auto_switch_elytra
license=MIT
credits=
description=When in the sky, it automatically switches to switch the upper elytra. \nAccepts multilines.
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)

# Optional Config UI Dependencies
cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8
yacl_version_fabric=3.9.3+26.1-fabric
yacl_version_neoforge=3.9.3+26.1-neoforge

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
