# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.20.6
maven_group=cn.com.fakeneko
archives_name=auto_switch_elytra
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.20.6
# Dependencies
fabric_loader_version=0.16.10
fabric_api_version=0.100.8+1.20.6
neoforge_version=20.6.124

cloth_config_version=14.0.139
modmenu_version=10.0.0
yacl_version_base=3.6.1+1.20.6
